const ProfileActionTypes = {
  PROFILE_UPDATE_START: "PROFILE_UPDATE_START",
  PROFILE_UPDATE_SUCCESS: "PROFILE_UPDATE_SUCCESS",
  PROFILE_UPDATE_FAILURE: "PROFILE_UPDATE_FAILURE",
};

export default ProfileActionTypes;
