const BlogsCollectionActionTypes = {
  FETCH_BLOGS_COLLECTION_START: "FETCH_BLOGS_COLLECTION_START",
  FETCH_BLOGS_COLLECTION_SUCCESS: "FETCH_BLOGS_COLLECTION_SUCCESS",
  FETCH_BLOGS_COLLECTION_FAILURE: "FETCH_BLOGS_COLLECTION_FAILURE",
};

export default BlogsCollectionActionTypes;
